"""
HydroDyn input file generator for offshore hydrodynamic loads.

Generates the HydroDyn input file matching OpenFAST v3.5.x parse order.
Supports both fixed-bottom (Morison) and floating (potential flow) platforms.
"""

from __future__ import annotations
from dataclasses import dataclass, field


@dataclass
class HydroDynConfig:
    """Configuration for HydroDyn input file."""

    # --- Environmental ---
    echo: bool = False
    wtr_dens: float = 1025.0
    wtr_dpth: float = 30.0
    msl2swl: float = 0.0

    # --- Waves ---
    wave_mod: int = 2           # 0=none, 1=regular (Airy), 2=JONSWAP/PM, 3=white noise, 4=user, 5=GH Bladed
    wave_st_mod: int = 0        # 0=none, 1=Chapman
    wave_t_max: float = 3600.0
    wave_dt: float = 0.25
    wave_hs: float = 1.5        # Significant wave height (m)
    wave_tp: float = 8.0        # Peak spectral period (s)
    wave_peak_sh_p: str = "DEFAULT"  # Peak shape parameter
    wave_dir: float = 0.0       # Wave direction (deg)
    wave_dir_mod: int = 0       # 0=none, 1=COS2S
    wave_dir_spread: float = 1.0
    wave_n_dir: int = 1
    wave_dir_range: float = 90.0
    wave_seed1: int = 123456789
    wave_seed2: str = "RANLUX"
    wave_n_elev: int = 0
    wave_elev_xi: list[float] = field(default_factory=list)
    wave_elev_yi: list[float] = field(default_factory=list)

    # --- 2nd-order waves ---
    wv_diff_qtf: bool = False
    wv_sum_qtf: bool = False
    wv_low_c_off: float = 0.0
    wv_hi_c_off: float = 500.0

    # --- Current ---
    curr_mod: int = 0           # 0=none, 1=standard, 2=user
    curr_ss_spd: float = 0.0   # Sub-surface current speed (m/s)
    curr_ss_dir: float = 0.0   # Sub-surface current direction (deg)
    curr_ns_ref: float = 20.0  # Near-surface current ref depth (m)
    curr_ns_spd: float = 0.0
    curr_ns_dir: float = 0.0
    curr_di_dir: float = 0.0

    # --- Floating platform (potential flow) ---
    pot_mod: int = 0            # 0=none, 1=without SS_Exctn, 2=with SS_Exctn
    exc_tn: int = 1
    rdtn_mod: int = 1
    rdtn_t_max: float = 60.0
    rdtn_dt: str = "DEFAULT"
    n_exctn_hdr: int = 7
    risc_dt: str = "DEFAULT"
    state_reduction: bool = False

    # --- Fixed-bottom (Morison strip theory) ---
    n_joints: int = 0
    joints: list[dict] = field(default_factory=list)
    n_prop_sets: int = 0
    prop_sets: list[dict] = field(default_factory=list)
    n_members: int = 0
    members: list[dict] = field(default_factory=list)
    n_fill_groups: int = 0
    n_mgr_props: int = 0
    n_mg_dpth: int = 0

    # --- Output ---
    hd_sum: bool = True
    out_all: bool = False
    out_switch: int = 1
    out_fmt: str = "ES11.4e2"


class HydroDynGenerator:
    """Generates HydroDyn input file for OpenFAST."""

    def generate(self, config: HydroDynConfig) -> str:
        lines: list[str] = []
        _a = lines.append

        # Header
        _a("------- HydroDyn INPUT FILE -------------------------------------------")
        _a("Generated by WindForge - HydroDyn v3.x input file")

        # Environmental
        _a("---------------------- ENVIRONMENTAL CONDITIONS --------------------------------")
        _a(f"{_flag(config.echo):<14s}   Echo           - Echo the input file data (flag)")
        _a(f"{config.wtr_dens:<14.1f}   WtrDens        - Water density (kg/m^3)")
        _a(f"{config.wtr_dpth:<14.1f}   WtrDpth        - Water depth (meters relative to MSL)")
        _a(f"{config.msl2swl:<14.1f}   MSL2SWL        - Offset between still-water level and mean sea level (m) [positive upward]")

        # Waves
        _a("---------------------- WAVES ---------------------------------------------------")
        _a(f"{config.wave_mod:<14d}   WaveMod        - Incident wave kinematics model {{0: none, 1: regular (Airy), 1P#: regular with user-specified phase, 2: JONSWAP/Pierson-Moskowitz spectrum (irregular), 3: White noise spectrum (irregular), 4: user-defined spectrum from routine UserWaveSpc (irregular), 5: Externally generated wave-Loss elevation time series, 6: Externally generated full wave-kinematics time series [option 6 is invalid for HD-standalone]}}")
        _a(f"{config.wave_st_mod:<14d}   WaveStMod      - Model for stretching incident wave kinematics to instantaneous free surface {{0: none=no stretching, 1: vertical stretching, 2: extrapolation stretching, 3: Wheeler stretching}}")
        _a(f"{config.wave_t_max:<14.1f}   WaveTMax       - Analysis time for incident wave calculations (sec) [unused when WaveMod=0 or 6]")
        _a(f"{config.wave_dt:<14.4f}   WaveDT         - Time step for incident wave calculations (sec) [unused when WaveMod=0 or 6]")
        _a(f"{config.wave_hs:<14.4f}   WaveHs         - Significant wave height of incident waves (meters) [used only when WaveMod=1, 2, or 3]")
        _a(f"{config.wave_tp:<14.4f}   WaveTp         - Peak-spectral period of incident waves (sec) [used only when WaveMod=1 or 2]")
        _a(f'{"\"" + config.wave_peak_sh_p + "\"":<14s}   WavePkShp      - Peak-shape parameter of JONSWAP spectrum {{or \"DEFAULT\"}} (-) [used only when WaveMod=2]')
        _a(f"{config.wave_dir:<14.4f}   WaveDir        - Incident wave propagation heading direction (degrees) [unused when WaveMod=0 or 6]")
        _a(f"{config.wave_dir_mod:<14d}   WaveDirMod     - Directional spreading function {{0: none, 1: COS2S}} (-) [only used when WaveMod=2,3, or 4]")
        _a(f"{config.wave_dir_spread:<14.1f}   WaveDirSpread  - Wave direction spreading coefficient (only used when WaveDirMod=1)")
        _a(f"{config.wave_n_dir:<14d}   WaveNDir       - Number of wave directions (-) [only used when WaveDirMod=1]")
        _a(f"{config.wave_dir_range:<14.1f}   WaveDirRange   - Range of wave directions (full range: WaveDir +/- WaveDirRange/2) (degrees) [only used when WaveDirMod=1]")
        _a(f"{config.wave_seed1:<14d}   WaveSeed(1)    - First random seed of incident waves [-2147483648 to 2147483647] (-)")
        _a(f'{"\"" + config.wave_seed2 + "\"":<14s}   WaveSeed(2)    - Second random seed (-) [\"RANLUX\" or \"RNSNLW\"]')
        _a(f"{config.wave_n_elev:<14d}   WaveNDAmp      - Number of points where the incident wave elevations can be computed (-) [only used when WaveMod>0]")

        # 2nd order waves
        _a("---------------------- 2ND-ORDER WAVES ----------------------------------------")
        _a(f"{_flag(config.wv_diff_qtf):<14s}   WvDiffQTF      - Full difference-frequency 2nd-order wave kinematics (flag)")
        _a(f"{_flag(config.wv_sum_qtf):<14s}   WvSumQTF       - Full summation-frequency 2nd-order wave kinematics (flag)")
        _a(f"{config.wv_low_c_off:<14.4f}   WvLowCOffD     - Low frequency cutoff used in the difference-frequencies (rad/s)")
        _a(f"{config.wv_hi_c_off:<14.4f}   WvHiCOffD      - High frequency cutoff used in the difference-frequencies (rad/s)")
        _a(f"{config.wv_low_c_off:<14.4f}   WvLowCOffS     - Low frequency cutoff used in the summation-frequencies (rad/s)")
        _a(f"{config.wv_hi_c_off:<14.4f}   WvHiCOffS      - High frequency cutoff used in the summation-frequencies (rad/s)")

        # Current
        _a("---------------------- CURRENT -------------------------------------------------")
        _a(f"{config.curr_mod:<14d}   CurrMod        - Current profile model {{0: none, 1: standard, 2: user-defined from routine UserCurrent}} (-)")
        _a(f"{config.curr_ss_spd:<14.4f}   CurrSSV0       - Sub-surface current velocity at still water level (m/s) [used only when CurrMod=1]")
        _a(f'{"\"DEFAULT\"":<14s}   CurrSSDir      - Sub-surface current heading direction (deg) or DEFAULT [used only when CurrMod=1]')
        _a(f"{config.curr_ns_ref:<14.1f}   CurrNSRef      - Near-surface current reference depth (meters) [used only when CurrMod=1]")
        _a(f"{config.curr_ns_spd:<14.4f}   CurrNSV0       - Near-surface current velocity at still water level (m/s) [used only when CurrMod=1]")
        _a(f"{config.curr_ns_dir:<14.1f}   CurrNSDir      - Near-surface current heading direction (degrees) [used only when CurrMod=1]")
        _a(f"{config.curr_di_dir:<14.1f}   CurrDIDir      - Depth-independent current heading direction (degrees) [used only when CurrMod=1]")
        _a(f"{0.0:<14.4f}   CurrDIV        - Depth-independent current velocity (m/s) [used only when CurrMod=1]")

        # Floating platform / WAMIT
        _a("---------------------- FLOATING PLATFORM ----------------------------------------")
        _a(f"{config.pot_mod:<14d}   PotMod         - Potential-flow model indicator (switch) {{0: none=no potential flow, 1: frequency-to-time-domain transforms based on WAMIT output, 2: fluid-impulse theory (FIT)}}")
        _a(f"{config.exc_tn:<14d}   ExctnMod       - Wave-excitation model {{0: no wave-Loss excitation calculation, 1: DFT, 2: state-space}} [used only when PotMod=1]")
        _a(f"{config.rdtn_mod:<14d}   RdtnMod        - Radiation memory-effect model {{0: no memory-effect calculation, 1: convolution, 2: state-space}} [used only when PotMod=1]")
        _a(f"{config.rdtn_t_max:<14.1f}   RdtnTMax       - Analysis time for wave radiation kernel calculations (sec) [used only when PotMod=1]")
        _a(f'{"\"DEFAULT\"":<14s}   RdtnDT         - Time step for wave radiation kernel calculations (sec) [used only when PotMod=1]')

        # Morison (fixed-bottom members)
        _a("---------------------- STRIPS THEORY OPTIONS (ACTIVE WHEN POTMOD=0) ----------")
        _a(f"{config.n_joints:<14d}   NJoints        - Number of joints (-)")
        if config.n_joints > 0 and config.joints:
            _a("   JointID   JointXss   JointYss   JointZss   JointType   JointDirX   JointDirY   JointDirZ   JointStiff")
            _a("   (-)       (m)        (m)        (m)        (-)         (-)         (-)         (-)         (Nm/rad)")
            for j in config.joints:
                jid = j.get("id", 0)
                x = j.get("x", 0.0)
                y = j.get("y", 0.0)
                z = j.get("z", 0.0)
                jtype = j.get("type_int", 1)
                _a(f"   {jid:<8d}{x:<11.3f}{y:<11.3f}{z:<11.3f}{jtype:<12d}{'0.0':<12s}{'0.0':<12s}{'0.0':<12s}{'0.0'}")
        _a(f"{config.n_prop_sets:<14d}   NPropSets      - Number of member property sets (-)")
        if config.n_prop_sets > 0 and config.prop_sets:
            _a("   PropSetID   PropD   PropThck")
            _a("   (-)         (m)     (m)")
            for ps in config.prop_sets:
                pid = ps.get("id", 0)
                d = ps.get("diameter", 10.0)
                t = ps.get("thickness", 0.06)
                _a(f"   {pid:<12d}{d:<8.3f}{t:<8.4f}")
        _a(f"{config.n_members:<14d}   NMembers       - Number of members (-)")
        if config.n_members > 0 and config.members:
            _a("   MemberID   MJointID1   MJointID2   MPropSetID1   MPropSetID2   MDivSize   MCoefMod   PropPot")
            _a("   (-)        (-)         (-)         (-)           (-)           (m)        (switch)   (flag)")
            for m in config.members:
                mid = m.get("id", 0)
                j1 = m.get("joint1", 0)
                j2 = m.get("joint2", 0)
                ps1 = m.get("prop_id", 1)
                ps2 = m.get("prop_id2", ps1)
                _a(f"   {mid:<10d}{j1:<12d}{j2:<14d}{ps1:<14d}{ps2:<14d}{'1.0':<11s}{'1':<11s}{'FALSE'}")
        _a(f"{config.n_fill_groups:<14d}   NFillGroups    - Number of filled fluid groups (-)")
        _a(f"{config.n_mgr_props:<14d}   NMGDepths      - Number of marine-growth depth stations (-)")

        # Output
        _a("---------------------- OUTPUT --------------------------------------------------")
        _a(f"{_flag(config.hd_sum):<14s}   HDSum          - Output a summary file [flag]")
        _a(f"{_flag(config.out_all):<14s}   OutAll         - Output all user-specified member and joint loads (flag)")
        _a(f"{config.out_switch:<14d}   OutSwtch       - Output requested channels to: [1=HydroDyn.out, 2=GlueCode.out, 3=both] (-)")
        _a(f'{"\"" + config.out_fmt + "\"":<14s}   OutFmt         - Output format for numerical results (quoted string)')
        _a("              OutList        - The next line(s) contains a list of output parameters. See OutListParameters.xlsx for a listing of available output channels, (-)")
        _a('"Wave1Elev"')
        _a("END of output channels and end of file. (the word \"END\" must appear in the above line)")

        return "\n".join(lines) + "\n"


def _flag(value: bool) -> str:
    return "True" if value else "False"
