"""
InflowWind input file generator for OpenFAST v4.1.2.

Generates the InflowWind input file that specifies wind inflow conditions.
Supports:
  - WindType=1: Steady (uniform) wind
  - WindType=3: TurbSim full-field binary wind file
  - WindType=4: Bladed-style full-field binary wind file

Format verified against:
  r-test/v4.1.2/glue-codes/openfast/5MW_Baseline/NRELOffshrBsline5MW_InflowWind_12mps.dat
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import IntEnum
from typing import Optional


class WindType(IntEnum):
    """InflowWind wind data source type."""
    STEADY = 1
    UNIFORM = 2
    TURBSIM_FF = 3
    BLADED_FF = 4
    HAWC = 5
    USER = 6
    EXTERNAL = 7


@dataclass
class InflowWindConfig:
    """Configuration for the InflowWind input file (v4.1.2 format)."""

    # --- General ---
    echo: bool = False
    wind_type: WindType = WindType.TURBSIM_FF
    propagation_dir: float = 0.0     # Wind propagation direction (deg, met convention)
    vflow_ang: float = 0.0           # Upflow angle (deg)
    vel_interp_cubic: bool = False   # Use cubic interpolation for velocity in time
    n_wind_vel: int = 1              # Number of wind velocity points
    wind_vx_list: float = 0.0
    wind_vy_list: float = 0.0
    wind_vz_list: float = 90.0      # Default to hub height

    # --- Steady Wind (WindType=1) ---
    h_wind_speed: float = 11.4       # Horizontal wind speed (m/s)
    ref_ht: float = 90.0             # Reference height for horizontal wind speed (m)
    pl_exp: float = 0.2              # Power law exponent (-)

    # --- Uniform Wind (WindType=2) ---
    uniform_filename: str = "unused"
    ref_ht_uni: float = 90.0
    ref_length: float = 125.88

    # --- TurbSim Full-Field (WindType=3) ---
    turbsim_filename: str = "TurbSim.bts"  # Path to TurbSim binary FF wind file

    # --- Bladed-Style Full-Field (WindType=4 or 7) ---
    bladed_filename: str = "unused"  # Root name of Bladed-style wind files
    tower_file: bool = False         # Tower wind file exists (.twr)

    # --- HAWC (WindType=5) ---
    hawc_filename_u: str = "unused"
    hawc_filename_v: str = "unused"
    hawc_filename_w: str = "unused"
    hawc_nx: int = 64
    hawc_ny: int = 32
    hawc_nz: int = 32
    hawc_dx: float = 16.0
    hawc_dy: float = 3.0
    hawc_dz: float = 3.0
    hawc_ref_ht: float = 90.0
    hawc_scale_method: int = 2
    hawc_sfx: float = 1.0
    hawc_sfy: float = 1.0
    hawc_sfz: float = 1.0
    hawc_sigma_fx: float = 1.2
    hawc_sigma_fy: float = 0.8
    hawc_sigma_fz: float = 0.2
    hawc_uref: float = 12.0
    hawc_wind_profile: int = 2
    hawc_pl_exp: float = 0.2
    hawc_z0: float = 0.03
    hawc_x_offset: float = 0.0

    # --- LIDAR Parameters ---
    sensor_type: int = 0
    num_pulse_gate: int = 0
    pulse_spacing: float = 30.0
    num_beam: int = 0
    focal_dist_x: float = -200.0
    focal_dist_y: float = 0.0
    focal_dist_z: float = 0.0
    rotor_apex_offset: tuple[float, float, float] = (0.0, 0.0, 0.0)
    uref_lid: float = 17.0
    measurement_interval: float = 0.25
    lid_radial_vel: bool = False
    consider_hub_motion: int = 1

    # --- Output ---
    sum_print: bool = False
    out_list: list[str] = field(default_factory=lambda: [
        '"Wind1VelX"', '"Wind1VelY"', '"Wind1VelZ"',
    ])


class InflowWindGenerator:
    """Generates InflowWind input files for OpenFAST v4.1.2 simulations."""

    def generate_inflowwind_file(self, config: InflowWindConfig) -> str:
        """Generate the InflowWind input file in v4.1.2 format.

        Parameters
        ----------
        config : InflowWindConfig
            Complete InflowWind configuration.

        Returns
        -------
        str
            Complete InflowWind input file content.
        """
        lines: list[str] = []
        _a = lines.append
        _f = _flag

        _a("------- InflowWind INPUT FILE -------------------------------------------------------------------------")
        _a("Generated by WindForge - InflowWind input file")

        # --- General ---
        _a("---------------------------------------------------------------------------------------------------------------")
        _a(f"{_f(config.echo):<14s}   Echo           - Echo input data to <RootName>.ech (flag)")
        _a(f"{int(config.wind_type):<14d}   WindType       - switch for wind file type (1=steady; 2=uniform; 3=binary TurbSim FF; 4=binary Bladed-style FF; 5=HAWC format; 6=User defined; 7=native Bladed FF)")
        _a(f"{config.propagation_dir:<14.0f}   PropagationDir - Direction of wind propagation (meteorological rotation from aligned with X (positive rotates towards -Y) -- degrees) (not used for native Bladed format WindType=7)")
        _a(f"{config.vflow_ang:<14.0f}   VFlowAng       - Upflow angle (degrees) (not used for native Bladed format WindType=7)")
        _a(f"{_f(config.vel_interp_cubic):<14s}   VelInterpCubic - Use cubic interpolation for velocity in time (false=linear, true=cubic) [Used with WindType=2,3,4,5,7]")
        _a(f"{config.n_wind_vel:<14d}   NWindVel       - Number of points to output the wind velocity    (0 to 9)")
        _a(f"{config.wind_vx_list:<14.0f}   WindVxiList    - List of coordinates in the inertial X direction (m)")
        _a(f"{config.wind_vy_list:<14.0f}   WindVyiList    - List of coordinates in the inertial Y direction (m)")
        _a(f"{config.wind_vz_list:<14.0f}   WindVziList    - List of coordinates in the inertial Z direction (m)")

        # --- Steady Wind ---
        _a("================== Parameters for Steady Wind Conditions [used only for WindType = 1] =========================")
        _a(f"{config.h_wind_speed:<14.0f}   HWindSpeed     - Horizontal wind speed                           (m/s)")
        _a(f"{config.ref_ht:<14.0f}   RefHt          - Reference height for horizontal wind speed      (m)")
        _a(f"{config.pl_exp:<14.1f}   PLExp          - Power law exponent                              (-)")

        # --- Uniform Wind ---
        _a("================== Parameters for Uniform wind file   [used only for WindType = 2] ============================")
        uni_fn = '"' + config.uniform_filename + '"'
        _a(f"{uni_fn:<40s}   FileName_Uni   - Filename of time series data for uniform wind field.      (-)")
        _a(f"{config.ref_ht_uni:<14.0f}   RefHt_Uni      - Reference height for horizontal wind speed                (m)")
        _a(f"{config.ref_length:<14.2f}   RefLength      - Reference length for linear horizontal and vertical sheer (-)")

        # --- TurbSim FF ---
        _a("================== Parameters for Binary TurbSim Full-Field files   [used only for WindType = 3] ==============")
        bts_fn = '"' + config.turbsim_filename + '"'
        _a(f"{bts_fn:<40s}   FileName_BTS   - Name of the Full field wind file to use (.bts)")

        # --- Bladed-style FF ---
        _a("================== Parameters for Binary Bladed-style Full-Field files   [used only for WindType = 4 or WindType = 7] =========")
        bladed_fn = '"' + config.bladed_filename + '"'
        _a(f"{bladed_fn:<40s}   FileNameRoot   - WindType=4: Rootname of the full-field wind file to use (.wnd, .sum); WindType=7: name of the intermediate file with wind scaling values")
        _a(f"{_f(config.tower_file):<14s}   TowerFile      - Have tower file (.twr) (flag) ignored when WindType = 7")

        # --- HAWC ---
        _a("================== Parameters for HAWC-format binary files  [Only used with WindType = 5] =====================")
        _a(f'{"\"" + config.hawc_filename_u + "\"":<40s}   FileName_u     - name of the file containing the u-component fluctuating wind (.bin)')
        _a(f'{"\"" + config.hawc_filename_v + "\"":<40s}   FileName_v     - name of the file containing the v-component fluctuating wind (.bin)')
        _a(f'{"\"" + config.hawc_filename_w + "\"":<40s}   FileName_w     - name of the file containing the w-component fluctuating wind (.bin)')
        _a(f"{config.hawc_nx:<14d}   nx             - number of grids in the x direction (in the 3 files above) (-)")
        _a(f"{config.hawc_ny:<14d}   ny             - number of grids in the y direction (in the 3 files above) (-)")
        _a(f"{config.hawc_nz:<14d}   nz             - number of grids in the z direction (in the 3 files above) (-)")
        _a(f"{config.hawc_dx:<14.0f}   dx             - distance (in meters) between points in the x direction    (m)")
        _a(f"{config.hawc_dy:<14.0f}   dy             - distance (in meters) between points in the y direction    (m)")
        _a(f"{config.hawc_dz:<14.0f}   dz             - distance (in meters) between points in the z direction    (m)")
        _a(f"{config.hawc_ref_ht:<14.0f}   RefHt_Hawc     - reference height; the height (in meters) of the vertical center of the grid (m)")
        _a("  -------------   Scaling parameters for turbulence   ---------------------------------------------------------")
        _a(f"{config.hawc_scale_method:<14d}   ScaleMethod    - Turbulence scaling method   [0 = none, 1 = direct scaling, 2 = calculate scaling factor based on a desired standard deviation]")
        _a(f"{config.hawc_sfx:<14.0f}   SFx            - Turbulence scaling factor for the x direction (-)   [ScaleMethod=1]")
        _a(f"{config.hawc_sfy:<14.0f}   SFy            - Turbulence scaling factor for the y direction (-)   [ScaleMethod=1]")
        _a(f"{config.hawc_sfz:<14.0f}   SFz            - Turbulence scaling factor for the z direction (-)   [ScaleMethod=1]")
        _a(f"{config.hawc_sigma_fx:<14.1f}   SigmaFx        - Turbulence standard deviation to calculate scaling from in x direction (m/s)    [ScaleMethod=2]")
        _a(f"{config.hawc_sigma_fy:<14.1f}   SigmaFy        - Turbulence standard deviation to calculate scaling from in y direction (m/s)    [ScaleMethod=2]")
        _a(f"{config.hawc_sigma_fz:<14.1f}   SigmaFz        - Turbulence standard deviation to calculate scaling from in z direction (m/s)    [ScaleMethod=2]")
        _a("  -------------   Mean wind profile parameters (added to HAWC-format files)   ---------------------------------")
        _a(f"{config.hawc_uref:<14.0f}   URef           - Mean u-component wind speed at the reference height (m/s)")
        _a(f"{config.hawc_wind_profile:<14d}   WindProfile    - Wind profile type (0=constant;1=logarithmic,2=power law)")
        _a(f"{config.hawc_pl_exp:<14.1f}   PLExp_Hawc     - Power law exponent (-) (used for PL wind profile type only)")
        _a(f"{config.hawc_z0:<14.2f}   Z0             - Surface roughness length (m) (used for LG wind profile type only)")
        _a(f"{config.hawc_x_offset:<14.0f}   XOffset        - Initial offset in +x direction (shift of wind box)")

        # --- LIDAR Parameters ---
        _a("================== LIDAR Parameters ===========================================================================")
        _a(f"{config.sensor_type:<14d}   SensorType          - Switch for lidar configuration (0 = None, 1 = Single Point Beam(s), 2 = Continuous, 3 = Pulsed)")
        _a(f"{config.num_pulse_gate:<14d}   NumPulseGate        - Number of lidar measurement gates (used when SensorType = 3)")
        _a(f"{config.pulse_spacing:<14.0f}   PulseSpacing        - Distance between range gates (m) (used when SensorType = 3)")
        _a(f"{config.num_beam:<14d}   NumBeam             - Number of lidar measurement beams (0-5)(used when SensorType = 1)")
        _a(f"{config.focal_dist_x:<14.0f}   FocalDistanceX      - Focal distance co-ordinates of the lidar beam in the x direction (relative to hub height) (only first coordinate used for SensorType 2 and 3) (m)")
        _a(f"{config.focal_dist_y:<14.0f}   FocalDistanceY      - Focal distance co-ordinates of the lidar beam in the y direction (relative to hub height) (only first coordinate used for SensorType 2 and 3) (m)")
        _a(f"{config.focal_dist_z:<14.0f}   FocalDistanceZ      - Focal distance co-ordinates of the lidar beam in the z direction (relative to hub height) (only first coordinate used for SensorType 2 and 3) (m)")
        offset_str = ", ".join(f"{v:10.0f}" for v in config.rotor_apex_offset)
        _a(f"{offset_str}    RotorApexOffsetPos  - Offset of the lidar from hub height (m)")
        _a(f"{config.uref_lid:<14.0f}   URefLid             - Reference average wind speed for the lidar[m/s]")
        _a(f"{config.measurement_interval:<14.2f}   MeasurementInterval - Time between each measurement [s]")
        _a(f"{_f(config.lid_radial_vel):<14s}   LidRadialVel        - TRUE => return radial component, FALSE => return 'x' direction estimate")
        _a(f"{config.consider_hub_motion:<14d}   ConsiderHubMotion   - Flag whether to consider the hub motion's impact on Lidar measurements")

        # --- Output ---
        _a("====================== OUTPUT ==================================================")
        _a(f"{_f(config.sum_print):<14s}   SumPrint     - Print summary data to <RootName>.IfW.sum (flag)")
        _a("              OutList      - The next line(s) contains a list of output parameters.  See OutListParameters.xlsx for a listing of available output channels, (-)")
        for out in config.out_list:
            _a(out)
        _a('END of input file (the word "END" must appear in the first 3 columns of this last OutList line)')
        _a("---------------------------------------------------------------------------------------")

        return "\n".join(lines) + "\n"


def _flag(value: bool) -> str:
    """Convert a boolean to OpenFAST flag format."""
    return "True" if value else "False"
