"""
MoorDyn input file generator for mooring system dynamics.

Generates MoorDyn v2 input file matching OpenFAST v3.5.x.
Used for floating platforms (spar, semi-submersible, TLP).
"""

from __future__ import annotations
from dataclasses import dataclass, field


@dataclass
class MoorDynConfig:
    """Configuration for MoorDyn input file."""

    echo: bool = False
    dt_mooring: float = 0.001
    t_max: float = 660.0

    # Line types
    line_types: list[dict] = field(default_factory=list)
    # Each: {name, diam, mass_den, EA, BA, EI, cd, ca, cdax, caax}

    # Rod types (optional)
    rod_types: list[dict] = field(default_factory=list)

    # Points (anchors, fairleads, connections)
    points: list[dict] = field(default_factory=list)
    # Each: {id, type, x, y, z, mass, volume, cd_a, ca_a}
    # type: "Fixed" (anchor), "Vessel" (fairlead), "Connect" (free)

    # Lines
    mooring_lines: list[dict] = field(default_factory=list)
    # Each: {id, line_type, attach_a, attach_b, unstr_len, n_segs}

    # Solver options
    dtm: float = 0.001
    kb_default: float = 3.0e6
    cb_default: float = 3.0e5
    t_max_ic: float = 120.0
    cd_scl: float = 1.0
    th_ic: float = 0.01


class MoorDynGenerator:
    """Generates MoorDyn v2 input file for OpenFAST."""

    def generate(self, config: MoorDynConfig) -> str:
        lines: list[str] = []
        _a = lines.append

        # Header
        _a("--------------------- MoorDyn Input File ------------------------------------")
        _a("Generated by WindForge - MoorDyn v2 input file for floating platform")

        _a(f"{_flag(config.echo):<14s}   Echo           - echo the input file data (flag)")

        # Line types
        _a("----------------------- LINE TYPES ------------------------------------------")
        _a(f"{'Name':<12s}  {'Diam':<8s}  {'MassDen':<10s}  {'EA':<12s}  {'BA/-zeta':<10s}  {'EI':<10s}  {'Cd':<6s}  {'Ca':<6s}  {'CdAx':<6s}  {'CaAx':<6s}")
        _a(f"{'(-)':<12s}  {'(m)':<8s}  {'(kg/m)':<10s}  {'(N)':<12s}  {'(N-s/-)':<10s}  {'(N-m^2)':<10s}  {'(-)':<6s}  {'(-)':<6s}  {'(-)':<6s}  {'(-)':<6s}")
        for lt in config.line_types:
            name = lt.get("name", "chain")
            diam = lt.get("diam", 0.0766)
            mass = lt.get("mass_den", 113.35)
            ea = lt.get("EA", 7.536e8)
            ba = lt.get("BA", -1.0)
            ei = lt.get("EI", 0.0)
            cd = lt.get("cd", 1.0)
            ca = lt.get("ca", 1.0)
            cdax = lt.get("cdax", 0.0)
            caax = lt.get("caax", 0.0)
            _a(f"{name:<12s}  {diam:<8.4f}  {mass:<10.2f}  {ea:<12.3E}  {ba:<10.1f}  {ei:<10.1f}  {cd:<6.1f}  {ca:<6.1f}  {cdax:<6.1f}  {caax:<6.1f}")

        # Rod types (empty for most cases)
        _a("----------------------- ROD TYPES -------------------------------------------")
        _a(f"{'Name':<12s}  {'Diam':<8s}  {'MassDen':<10s}  {'Cd':<6s}  {'Ca':<6s}  {'CdEnd':<6s}  {'CaEnd':<6s}")
        _a(f"{'(-)':<12s}  {'(m)':<8s}  {'(kg/m)':<10s}  {'(-)':<6s}  {'(-)':<6s}  {'(-)':<6s}  {'(-)':<6s}")

        # Bodies (empty for standard mooring)
        _a("----------------------- BODIES ----------------------------------------------")
        _a(f"{'ID':<6s}  {'Attachment':<12s}  {'X0':<8s}  {'Y0':<8s}  {'Z0':<8s}  {'r0':<6s}  {'p0':<6s}  {'y0':<6s}  {'Mass':<10s}  {'CG*':<8s}  {'I*':<8s}  {'Volume':<10s}  {'CdA*':<8s}  {'Ca*':<6s}")
        _a(f"{'(-)':<6s}  {'(-)':<12s}  {'(m)':<8s}  {'(m)':<8s}  {'(m)':<8s}  {'(deg)':<6s}  {'(deg)':<6s}  {'(deg)':<6s}  {'(kg)':<10s}  {'(m)':<8s}  {'(kg-m^2)':<8s}  {'(m^3)':<10s}  {'(m^2)':<8s}  {'(-)':<6s}")

        # Rods (empty for standard mooring)
        _a("----------------------- RODS ------------------------------------------------")
        _a(f"{'ID':<6s}  {'RodType':<12s}  {'Attachment':<12s}  {'Xa':<8s}  {'Ya':<8s}  {'Za':<8s}  {'Xb':<8s}  {'Yb':<8s}  {'Zb':<8s}  {'NumSegs':<8s}  {'Flags':<8s}")
        _a(f"{'(-)':<6s}  {'(-)':<12s}  {'(-)':<12s}  {'(m)':<8s}  {'(m)':<8s}  {'(m)':<8s}  {'(m)':<8s}  {'(m)':<8s}  {'(m)':<8s}  {'(-)':<8s}  {'(-)':<8s}")

        # Points
        _a("----------------------- POINTS ----------------------------------------------")
        _a(f"{'ID':<6s}  {'Attachment':<12s}  {'X':<10s}  {'Y':<10s}  {'Z':<10s}  {'Mass':<10s}  {'Volume':<10s}  {'CdA':<8s}  {'Ca':<6s}")
        _a(f"{'(-)':<6s}  {'(-)':<12s}  {'(m)':<10s}  {'(m)':<10s}  {'(m)':<10s}  {'(kg)':<10s}  {'(m^3)':<10s}  {'(m^2)':<8s}  {'(-)':<6s}")
        for pt in config.points:
            pid = pt.get("id", 0)
            ptype = pt.get("type", "Fixed")
            x = pt.get("x", 0.0)
            y = pt.get("y", 0.0)
            z = pt.get("z", 0.0)
            mass = pt.get("mass", 0.0)
            vol = pt.get("volume", 0.0)
            cda = pt.get("cda", 0.0)
            ca = pt.get("ca", 0.0)
            _a(f"{pid:<6d}  {ptype:<12s}  {x:<10.2f}  {y:<10.2f}  {z:<10.2f}  {mass:<10.1f}  {vol:<10.4f}  {cda:<8.2f}  {ca:<6.1f}")

        # Lines
        _a("----------------------- LINES -----------------------------------------------")
        _a(f"{'ID':<6s}  {'LineType':<12s}  {'AttachA':<8s}  {'AttachB':<8s}  {'UnstrLen':<10s}  {'NumSegs':<8s}  {'Flags':<8s}")
        _a(f"{'(-)':<6s}  {'(-)':<12s}  {'(-)':<8s}  {'(-)':<8s}  {'(m)':<10s}  {'(-)':<8s}  {'(-)':<8s}")
        for ln in config.mooring_lines:
            lid = ln.get("id", 0)
            ltype = ln.get("line_type", "chain")
            att_a = ln.get("attach_a", 0)
            att_b = ln.get("attach_b", 0)
            length = ln.get("unstr_len", 850.0)
            nsegs = ln.get("n_segs", 20)
            _a(f"{lid:<6d}  {ltype:<12s}  {att_a:<8d}  {att_b:<8d}  {length:<10.2f}  {nsegs:<8d}  {'-':<8s}")

        # Solver options
        _a("----------------------- SOLVER OPTIONS --------------------------------------")
        _a(f"{config.dtm:<14.6f}   dtM            - time step to use in mooring integration (s)")
        _a(f"{config.kb_default:<14.1f}   kbot           - bottom stiffness (Pa/m)")
        _a(f"{config.cb_default:<14.1f}   cbot           - bottom damping (Pa-s/m)")
        _a(f"{config.t_max_ic:<14.1f}   TmaxIC         - max time for initial condition convergence (s)")
        _a(f"{config.cd_scl:<14.4f}   CdScl          - scaling factor for CD (-)")
        _a(f"{config.th_ic:<14.4f}   threshIC       - threshold for initial condition convergence (-)")

        # Output
        _a("----------------------- OUTPUT ----------------------------------------------")
        _a("              OutList        - List of output channels")
        _a("END of output channels and end of file.")

        return "\n".join(lines) + "\n"


def _flag(value: bool) -> str:
    return "True" if value else "False"
