"""
SubDyn input file generator for substructure dynamics.

Generates SubDyn input file matching OpenFAST v3.5.x parse order.
Supports monopile and jacket substructures.
"""

from __future__ import annotations
from dataclasses import dataclass, field


@dataclass
class SubDynConfig:
    """Configuration for SubDyn input file."""

    echo: bool = False
    sd_delta_t: str = "DEFAULT"
    int_method: int = 4          # 1=RK4, 2=AB4, 3=ABM4, 4=AM2
    sttc_solve: bool = False

    # FEA and Craig-Bampton
    fea_mod: int = 3             # 1=Euler-Bernoulli, 3=Timoshenko
    n_div: int = 1
    cb_mod: bool = True
    n_modes: int = 8
    j_damp_ng: float = 1.0      # Damping ratio (%)
    gui_mod: int = 2             # 0=none, 1=Guyan, 2=Craig-Bampton, 3=SIM

    # Structure
    n_joints: int = 0
    joints: list[dict] = field(default_factory=list)
    n_react: int = 0
    react_joints: list[dict] = field(default_factory=list)
    n_interf: int = 0
    interf_joints: list[dict] = field(default_factory=list)
    n_members: int = 0
    members: list[dict] = field(default_factory=list)
    n_prop_sets: int = 0
    prop_sets: list[dict] = field(default_factory=list)

    # Concentrated masses
    n_cmass: int = 0
    cmass: list[dict] = field(default_factory=list)

    # Output
    sum_print: bool = True
    out_co_rd: str = "1"
    out_all: bool = True
    out_switch: int = 1
    out_fmt: str = "ES11.4e2"


class SubDynGenerator:
    """Generates SubDyn input file for OpenFAST."""

    def generate(self, config: SubDynConfig) -> str:
        lines: list[str] = []
        _a = lines.append

        # Header
        _a("------- SubDyn INPUT FILE -------------------------------------------")
        _a("Generated by WindForge - SubDyn v3.x input file")

        # Simulation control
        _a("---------------------- SIMULATION CONTROL ---------------------------------")
        _a(f"{_flag(config.echo):<14s}   Echo           - Echo input data to '<rootname>.SD.ech' (flag)")
        _a(f'{"\"" + config.sd_delta_t + "\"":<14s}   SDdeltaT       - Local Integration Step. If \"default\", the glue-code integration step will be used.')
        _a(f"{config.int_method:<14d}   IntMethod      - Integration Method [1/2/3/4 = RK4/AB4/ABM4/AM2].")
        _a(f"{_flag(config.sttc_solve):<14s}   SttcSolve      - Solve dynamics about static equilibrium point")

        # FEA and Craig-Bampton
        _a("---------------------- FEA and CRAIG-BAMPTON PARAMETERS -------------------")
        _a(f"{config.fea_mod:<14d}   FEMMod         - FEM switch: element model in the FEM. [1= Euler-Bernoulli(E-B); 2=Tapered E-B; 3=2-node Timoshenko; 4=2-node tapered Timoshenko]")
        _a(f"{config.n_div:<14d}   NDiv           - Number of sub-elements per member (-)")
        _a(f"{_flag(config.cb_mod):<14s}   CBMod          - [T/F] If True perform C-B reduction, else full FEM dofs will be retained. If True, selected Nmodes will be kept.")
        _a(f"{config.n_modes:<14d}   Nmodes         - Number of internal modes to retain (-)")
        _a(f"{config.j_damp_ng:<14.4f}   JDampings      - Damping Ratios for each retained mode (% of critical) If JDampings < Nmodes, flag error")
        _a(f"{config.gui_mod:<14d}   GuyanDampMod   - Guyan damping [0=none, 1=Rayleigh Damping, 2=user]")

        # Joints
        _a("---- STRUCTURE JOINTS -------------------------------------------------")
        _a(f"{config.n_joints:<14d}   NJoints        - Number of joints (-)")
        if config.n_joints > 0 and config.joints:
            _a("   JointID   JointXss   JointYss   JointZss   JointType   JointDirX   JointDirY   JointDirZ   JointStiff")
            _a("   (-)       (m)        (m)        (m)        (-)         (-)         (-)         (-)         (Nm/rad)")
            for j in config.joints:
                jid = j.get("id", 0)
                x = j.get("x", 0.0)
                y = j.get("y", 0.0)
                z = j.get("z", 0.0)
                jtype = j.get("type_int", 1)
                _a(f"   {jid:<8d}{x:<11.3f}{y:<11.3f}{z:<11.3f}{jtype:<12d}{'0.0':<12s}{'0.0':<12s}{'0.0':<12s}{'0.0'}")

        # Base reaction joints
        _a("---- BASE REACTION JOINTS ---------------------------------------------")
        _a(f"{config.n_react:<14d}   NReact         - Number of Joints with reaction support (-)")
        if config.n_react > 0 and config.react_joints:
            _a("   RJointID   RctTDXss   RctTDYss   RctTDZss   RctRDXss   RctRDYss   RctRDZss   SSIfile")
            _a("   (-)        (flag)     (flag)     (flag)     (flag)     (flag)     (flag)     (string)")
            for rj in config.react_joints:
                rjid = rj.get("id", 0)
                _a(f"   {rjid:<10d}{'1':<11s}{'1':<11s}{'1':<11s}{'1':<11s}{'1':<11s}{'1':<11s}{'\"\"'}")

        # Interface joints
        _a("---- INTERFACE JOINTS -------------------------------------------------")
        _a(f"{config.n_interf:<14d}   NInterf        - Number of interface joints locked to the Transition Piece (TP) (-)")
        if config.n_interf > 0 and config.interf_joints:
            _a("   IJointID   ItfTDXss   ItfTDYss   ItfTDZss   ItfRDXss   ItfRDYss   ItfRDZss")
            _a("   (-)        (flag)     (flag)     (flag)     (flag)     (flag)     (flag)")
            for ij in config.interf_joints:
                ijid = ij.get("id", 0)
                _a(f"   {ijid:<10d}{'1':<11s}{'1':<11s}{'1':<11s}{'1':<11s}{'1':<11s}{'1'}")

        # Members
        _a("---- MEMBERS ----------------------------------------------------------")
        _a(f"{config.n_members:<14d}   NMembers       - Number of frame members (-)")
        if config.n_members > 0 and config.members:
            _a("   MemberID   MJointID1   MJointID2   MPropSetID1   MPropSetID2   MType")
            _a("   (-)        (-)         (-)         (-)           (-)           (switch)")
            for m in config.members:
                mid = m.get("id", 0)
                j1 = m.get("joint1", 0)
                j2 = m.get("joint2", 0)
                ps = m.get("prop_id", 1)
                mtype = m.get("type", 1)
                _a(f"   {mid:<10d}{j1:<12d}{j2:<14d}{ps:<14d}{ps:<14d}{mtype}")

        # Member cross-section property sets
        _a("---- MEMBER CROSS-SECTION PROPERTY data 1/2 (Circular tube) ----------")
        _a(f"{config.n_prop_sets:<14d}   NPropSets      - Number of property sets (-)")
        if config.n_prop_sets > 0 and config.prop_sets:
            _a("   PropSetID   YoungE       ShearG       MatDens      XsijArea     XsijIxx      XsijIyy      XsijIzz      XsijJG")
            _a("   (-)         (N/m2)       (N/m2)       (kg/m3)      (m2)         (m4)         (m4)         (m4)         (m4)")
            for ps in config.prop_sets:
                pid = ps.get("id", 1)
                E = ps.get("E", 2.1e11)
                G = ps.get("G", 8.08e10)
                rho = ps.get("rho", 7850.0)
                D = ps.get("outer_diameter", 10.0)
                t = ps.get("wall_thickness", 0.06)
                import math
                r_o = D / 2.0
                r_i = r_o - t
                area = math.pi * (r_o**2 - r_i**2)
                I_val = math.pi / 4.0 * (r_o**4 - r_i**4)
                J = 2.0 * I_val
                _a(f"   {pid:<12d}{E:<13.3E}{G:<13.3E}{rho:<13.1f}{area:<13.4f}{I_val:<13.4E}{I_val:<13.4E}{'0.0':<13s}{J:<13.4E}")
        _a("---- SIMPLE HYDRODYNAMIC COEFFICIENTS (ACTIVE WHEN NMEMBERS>0) --------")
        _a("    SimplCd  SimplCdMG  SimplCa  SimplCaMG  SimplCp  SimplCpMG  SimplAxCd  SimplAxCdMG  SimplAxCa  SimplAxCaMG  SimplAxCp  SimplAxCpMG")
        _a("    (-)      (-)        (-)      (-)        (-)      (-)        (-)        (-)          (-)        (-)          (-)        (-)")
        _a("    1.0      1.0        1.0      1.0        1.0      1.0        0.0        0.0          1.0        1.0          1.0        1.0")

        # Concentrated masses
        _a("---- CONCENTRATED MASSES -----------------------------------------------")
        _a(f"{config.n_cmass:<14d}   NCmass         - Number of Concentrated masses (-)")

        # Output
        _a("---------------------- OUTPUT ------------------------------------------")
        _a(f"{_flag(config.sum_print):<14s}   SSSum          - Output a Summary File (flag)")
        _a(f"{_flag(config.out_all):<14s}   OutAll         - Output all member and joint loads (flag)")
        _a(f"{config.out_switch:<14d}   OutSwtch       - Output requested channels to: [1=<rootname>.SD.out, 2=<rootname>.out (GlueCode), 3=both]")
        _a("              OutList        - List of member forces to output (-)")
        _a("END of output channels and end of file.")

        return "\n".join(lines) + "\n"


def _flag(value: bool) -> str:
    return "True" if value else "False"
