"""add_offshore_fields

Revision ID: 442ce1bc9811
Revises: 5d1f2475d6c5
Create Date: 2026-02-27 12:06:26.547541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '442ce1bc9811'
down_revision: Union[str, Sequence[str], None] = '5d1f2475d6c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('platform_type', sa.String(length=30), nullable=False, server_default='onshore'))
    op.add_column('projects', sa.Column('water_depth', sa.Float(), nullable=True))
    op.add_column('turbine_models', sa.Column('substructure_config', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('turbine_models', sa.Column('hydrodyn_config', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('turbine_models', sa.Column('moordyn_config', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turbine_models', 'moordyn_config')
    op.drop_column('turbine_models', 'hydrodyn_config')
    op.drop_column('turbine_models', 'substructure_config')
    op.drop_column('projects', 'water_depth')
    op.drop_column('projects', 'platform_type')
    # ### end Alembic commands ###
